apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-activemq-config
data:
  {{- $root := .Values.activemq }}
  {{- with .Values.activemq.config }}
  ACTIVEMQ_DATA_DIR: {{ .data_directory | default "/opt/activemq/data" | quote }}
  ACTIVEMQ_DATA_DIR_SIZE: {{ .data_dir_size | default "100" | quote }}
  ACTIVEMQ_DATA_TMP_SIZE: {{ .data_tmp_size | default "50" | quote }}
  ACTIVEMQ_OPENWIRE_PORT: {{ .openwire_port | default "61616" | quote }}
  ACTIVEMQ_AMQP_PORT: {{ .amqp_port | default "5672" | quote }}
  ACTIVEMQ_STOMP_PORT: {{ .stomp_port | default "61613" | quote }}
  ACTIVEMQ_MQTT_PORT: {{ .mqtt_port | default "1883" | quote }}
  ACTIVEMQ_WS_PORT: {{ .ws_port | default "61614" | quote }}
  PROTECTED_BROKER: {{ include "secure_broker.isDefined" $root.secure_broker | quote }}
  ACTIVEMQ_SQL_DATASTORE: {{ $root.datastore.sql }}
  {{- end }}