{{- if and (not .Values.activemq.external_secret.enabled) (not .Values.activemq.extraEnvs) }}
{{- with .Values.activemq.secure_broker }}
{{- if eq ( include "secure_broker.isDefined" . ) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-activemq-broker-secrets
data:
  ACTIVEMQ_USERNAME: {{ required "Username to access broker is required when secured broker is enabled." .username | b64enc }}
  ACTIVEMQ_PASSWORD: {{ include "password.isValid" . | b64enc }}
{{- end }}
{{- end }}
{{- end }}