{{- if and (not .Values.activemq.external_secret.enabled) (not .Values.activemq.extraEnvs) }}
{{- if not .Values.activemq.web }}
{{- fail "If external secret is disabled, web admin password and username should be specified" }}
{{- end }}
{{- with .Values.activemq.web }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-activemq-ui-secrets
data:
  ACTIVEMQ_WEBADMIN_USERNAME: {{ required "Username to access ui is required." .username | b64enc }}
  ACTIVEMQ_WEBADMIN_PASSWORD: {{ include "password.isValid" . | b64enc }}
{{- end }}
{{- end }}