apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-activemq
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    io.kubernetes/app-name: {{ .Release.Name }}-activemq
    io.activemq/version: "5.10"
    {{- with .Values.activemq.config}}
  ports:
  - name: amq-openwire
    port: {{ .openwire_port }}
    targetPort: openwire
  - name: amq-amqp
    targetPort: amqp
    port: {{ .amqp_port }}
  - name: amq-stomp
    targetPort: stomp
    port: {{ .stomp_port }}
  - name: amq-mqtt
    targetPort: mqtt
    port: {{ .mqtt_port }}
  - name: amq-ws
    targetPort: ws
    port: {{ .ws_port }}
    {{- end }}