apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-activemq-ui-conf
data:
  activemq-ui.conf: |
      server {
          listen {{ .Values.web.service.port }};
          location ~ /(.*) {
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_pass http://activemq-ui;
          }
      }
      upstream activemq-ui {
        {{- include "web.proxy" . | indent 8 }}
      }