apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-activemq-ui
spec:
  {{- with .Values.web.service }}
  type: {{ .type }}
  selector:
    io.kubernetes/app-name: {{ $.Release.Name }}-activemq-ui
    io.activemq/version: "5.10"
  ports:
  - name: amq-ui
    targetPort: ui
    port: {{ .port }}
    {{- end }}